plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}
group = 'io.gizu.signer'
version = '0.1.0'
android {
  namespace 'io.gizu.signer'
  defaultConfig { minSdk 24; versionCode 1; versionName "0.1.0" }
  sourceSets.main.java.srcDirs += '../generated'
}
dependencies {
  implementation 'androidx.credentials:credentials:1.6.0'
  implementation 'androidx.credentials:credentials-play-services-auth:1.6.0'
  implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2'
  implementation 'net.java.dev.jna:jna:5.17.0@aar'
}
